name: Feature request
description: Suggest an improvement to the Adaptive DNA portal or viewers
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: User need / job to be done
      placeholder: As a … I want … so that …
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: What should we build? Any alternatives?
  - type: textarea
    id: impact
    attributes:
      label: Impact
      placeholder: Users affected, KPIs, timelines.
